[tool.poetry]
name = "pytestnew"
version = "0.1.0"
description = ""
authors = ["Krushovice <kickstar69@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^8.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
